### PR TITLE
Updated for v6.0, tried to align with MvcWeb example from piranha.core

### PR DESCRIPTION
**Pull request by i-love-code**
Updated these templates for v6.0, tried to align with "MvcWeb" project example from piranha.core.

Known issue
- In the MvcBlog example, the tag links that are meant to link to the filtered archive page do not work from inside a blog post (see video: https://i.gyazo.com/a5f2c60b64667f91e0a7d177217dad63.mp4) but I believe this is just a simple routing change within that view. I will add a commit to this PR if I resolve that.

### CODE REVIEW

**Comment by i-love-code** [comment]
Hopefully I'm not overlapping with an existing effort to update these templates. I needed to update them for an ongoing effort to get more developers internally to use Piranha, so I thought I'd contribute it too.

**Comment by tidyui** [comment]
Hi there! I realized after releasing the new templates on NuGet that I've accidentally updated the **old** repositories instead of this new one, so good call. I'll take a look and then I will archive the old repositories in favor of this one.

**Comment by tidyui** [comment]
And filter links on blog posts does not work in the old repositories either, so it's likely been this way from the beginning.

**Comment by i-love-code** [comment]
Ah that makes sense.. I forgot about the old repository! 

As for the blog post links for tags within, I figured as much. I didn't have the time to test it, but I doubted that any changes related to 6.0 could've caused it.

**Pull request merged**
